#!/bin/sh

set -x
aclocal -I config || exit 1
#libtoolize --automake --copy --force || exit 1
autoheader || exit 1
automake --add-missing --copy --force-missing --foreign || exit 1
#autoconf --force --warnings=all || exit 1
autoconf --force || exit 1
rm -fr autom4te*.cache
exit 0
